### ISSUE TITLE
ctrl.container.has is not a function

### ISSUE THREAD

**Issue by mathieu-morchipont** [vickramravichandran/angular-auto-complete#7]
I have an error "ctrl.container.has is not a function" line 255 after update 1.3.0 to 1.4.0

Thks

**Comment by vickramravichandran** [comment]
I think it now has a dependency on jQuery now: https://api.jquery.com/has/

Can you add jQuery to your page and let me know if that fixes it?

**Comment by mathieu-morchipont** [comment]
Good

**Comment by RobbertWolfs** [comment]
@vickramravichandran  Any solution without using jQuery? Because we don't have and want jQuery in our project and we updated to 1.4.2 and now we get the same error...

**Comment by vickramravichandran** [comment]
@RobbertWolfs Without jQuery I will need to implement the same using native JavaScript. See this from an earlier version https://github.com/vickramravichandran/angular-auto-complete/blob/v1.2.0/angular-auto-complete.js#L181

I went with jQuery because it was not working consistently across different browsers.

**Comment by RobbertWolfs** [comment]
Any idea which browsers? ;)

**Comment by vickramravichandran** [comment]
Chrome, Firefox and Safari.
